services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: dangarpra/chatbot-frontend:v1.0.1
    container_name: chatbot-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: dangarpra/chatbot-backend:v1.0.1
    container_name: chatbot-backend
    ports:
      - "5000:5000"
    environment:
      - COHERE_API_KEY=${COHERE_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT}
      - INDEX_NAME=desafiofinal 